import React from 'react';
import { motion } from 'framer-motion';
import { GlassCard, Badge } from '../components/ui/Components';
import { ShieldCheck, EyeOff, Lock, UserCheck, AlertTriangle } from 'lucide-react';

const ResponsibleAICenter = () => {
  return (
    <div className="space-y-8 max-w-5xl mx-auto">
      <motion.div initial={{ opacity: 0, scale: 0.95 }} animate={{ opacity: 1, scale: 1 }} transition={{ duration: 0.5 }} className="text-center py-10 px-4">
        <div className="w-20 h-20 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 flex items-center justify-center mx-auto mb-6 shadow-xl shadow-emerald-500/10">
           <ShieldCheck size={40} />
        </div>
        <h1 className="text-3xl font-bold text-white mb-4">Responsible AI & Privacy Center</h1>
        <p className="text-base text-slate-400 max-w-2xl mx-auto leading-relaxed">
          EduVerse AI is built on the principle that artificial intelligence should augment human empathy, not replace it. Our models are designed for pedagogical support, strictly adhering to privacy and consent frameworks.
        </p>
      </motion.div>

      <div className="grid md:grid-cols-2 gap-6">
        <GlassCard hover={false} className="p-8 border-t-2 border-t-brand-500">
           <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-brand-500/10 text-brand-400"><UserCheck size={20}/></div>
              <h3 className="text-lg font-semibold text-white">Human-In-The-Loop</h3>
           </div>
           <p className="text-sm text-slate-400 leading-relaxed mb-4">
             AI generated insights, including Engagement Scores and Learning States, are strictly indicators. 
             They do not trigger automated disciplinary actions, grading penalties, or permanent record alterations.
           </p>
           <div className="p-4 rounded-xl bg-dark-bg border border-dark-border flex items-start gap-3">
              <AlertTriangle size={16} className="text-amber-400 shrink-0 mt-0.5" />
              <p className="text-xs text-slate-300 leading-relaxed">
                Teachers are presented with evidence and must manually approve interventions or override AI assessments they deem contextually inaccurate.
              </p>
           </div>
        </GlassCard>

        <GlassCard hover={false} className="p-8 border-t-2 border-t-emerald-500">
           <div className="flex items-center gap-3 mb-6">
              <div className="p-2 rounded-lg bg-emerald-500/10 text-emerald-400"><EyeOff size={20}/></div>
              <h3 className="text-lg font-semibold text-white">Explicit Consent & Local Processing</h3>
           </div>
           <p className="text-sm text-slate-400 leading-relaxed mb-4">
             Camera and screen-activity analysis are entirely opt-in. Computer vision models are loaded locally in the browser utilizing TensorFlow.js or WebAssembly.
           </p>
           <div className="px-4 py-3 rounded-lg bg-emerald-500/10 border border-emerald-500/20 text-emerald-200 text-xs font-semibold inline-flex items-center gap-2">
              <Lock size={12} /> Zero video streams are transmitted to our servers tracking gaze/pose.
           </div>
        </GlassCard>
      </div>

      <GlassCard hover={false} className="p-0 overflow-hidden">
        <div className="bg-dark-bg/80 p-6 border-b border-dark-border">
           <h3 className="text-lg font-semibold text-white">Core Pillars of EduVerse AI Ethics</h3>
        </div>
        <div className="divide-y divide-dark-border">
           {[
              { title: 'Explainable AI Insights', desc: 'Every score or state generated by the system must display the "why" (the evidence timeline) alongside the "what". Hidden black-box scoring is prohibited.' },
              { title: 'Anti-Stigmatization Labeling', desc: 'The Digital Twin avoids terminology like "lazy" or "distracted" as definitive traits. Focus is strictly on temporal pedagogical states ("Struggling", "Needs Support").' },
              { title: 'Data Minimization', desc: 'Tracking telemetry is ephemeral. Long-term storage aggregates patterns into the Digital Twin, discarding raw session event logs.' },
              { title: 'Role-Based Data Obfuscation', desc: 'Parents and Students view abstracted, meaningful pedagogical insights rather than raw, potentially unnerving biometric telemetry like "Gaze Vector Y".' }
           ].map((pillar, i) => (
              <div key={i} className="p-6 flex flex-col md:flex-row gap-4 hover:bg-white/[0.02] transition-colors">
                 <div className="w-10 h-10 rounded-full border border-dark-border bg-dark-bg flex items-center justify-center text-slate-400 font-bold shrink-0">
                    {i + 1}
                 </div>
                 <div>
                    <h4 className="text-base font-semibold text-white mb-2">{pillar.title}</h4>
                    <p className="text-sm text-slate-400 leading-relaxed">{pillar.desc}</p>
                 </div>
              </div>
           ))}
        </div>
      </GlassCard>
    </div>
  );
};

export default ResponsibleAICenter;
